#! /usr/bin/env perl

use warnings;
use strict;
use POSIX qw (ceil);

srand 69;

local $SIG{__WARN__} = sub {};

my $what = shift @ARGV or die;
my $num = shift @ARGV or die;

my $fh = \*STDIN;
binmode ($fh, ':raw');

$/ = \4;
my $magic = unpack ("N", <$fh>);
die "wtf $magic" unless $magic == 2049;

my $n_items = unpack ("N", <$fh>);
warn "n_items = $n_items";

$/ = \1;

my @lines = map { $_->[0] } 
            sort { $a->[1] <=> $b->[1] } 
	    map { [ $_, rand () ] } 
	    <$fh>;

my $split = ceil ($n_items / $num);
my $start = ($what - 1) * $split;

my @data = splice (@lines, $start, $split);

binmode (\*STDOUT,':raw');
print pack ("N", $magic);
print pack ("N", scalar @data);

foreach my $d (@data)
  {
    print $d;
  }
